microservice-chart:
  image:
    repository: ghcr.io/pagopa/emd-notifier-sender
    tag: snapshot-MMC-358-update-filterEnabledList
    pullPolicy: Always

  ingress:
    host: "mdc.itn.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "768Mi"
      cpu: "150m"
    limits:
      memory: "1536Mi"
      cpu: "600m"

  autoscaling:
    enable: false

  envConfig:
    LOGGING_LEVEL_IT_GOV_PAGOPA_NOTIFIER: "DEBUG"
    MONGODB_DBNAME: mdc
    BENEFICIARY_RULE_BUILD_DELAY_DURATION: "150"
    APPLICATIONINSIGHTS_ROLE_NAME: "emdnotifiersender"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=7
      -Dio.netty.eventLoopThreads=100
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json
      -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n
      -Dcom.sun.management.jmxremote=true
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.rmi.port=3003
      -Djava.rmi.server.hostname=127.0.0.1
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false

  envSecret:
    MY_KV_SECRET: cstar-d-itn-dev-aks-apiserver-url
    MONGODB_URI: mongodb-connection-string
    KAFKA_MESSAGE_CORE_SASL_JAAS_CONFIG: evh-emd-courtesy-message-emd-courtesy-message-consumer-jaas-config-emd
    KAFKA_MESSAGE_CORE_OUT_SASL_JAAS_CONFIG: evh-emd-courtesy-message-emd-courtesy-message-producer-jaas-config-emd
    KAFKA_NOTIFY_ERROR_SASL_JAAS_CONFIG: evh-emd-notify-error-emd-notify-error-consumer-jaas-config-emd
    KAFKA_NOTIFY_ERROR_OUT_SASL_JAAS_CONFIG: evh-emd-notify-error-emd-notify-error-producer-jaas-config-emd

  keyvault:
    name: "cstar-d-itn-mdc-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
